version: '3.9'

services:
  server:
    image: twojsomsiad
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - twojsomsiad

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: twojsomsiad
    ports:
      - 5432:5432
    networks:
      - twojsomsiad

networks:
  twojsomsiad: